language: python
python:
  - "2.7"
  - "3.3"
install: 
  - "pip install -r requirements-testing.txt --use-mirrors"
  - "pip install coveralls"
  - "python setup.py install"
script: 
  nosetests --with-coverage --cover-package=nut2
after_success:
  coveralls
